version: "3.8"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurant_booking
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
  web:
    build:
      context: .
      target: base
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: "3000"
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    expose:
      - '3001'
    command: npm run dev
